// <auto-generated />
using DatabaseAccess;
using Interface.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace DatabaseAccess.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20180106114119_TestIncrementalMigration")]
    partial class TestIncrementalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Interface.Entities.LogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ItemNumber");

                    b.Property<int>("LogLineId");

                    b.HasKey("Id");

                    b.HasIndex("LogLineId");

                    b.ToTable("LogItems");
                });

            modelBuilder.Entity("Interface.Entities.LogLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Interface.Entities.LogItem", b =>
                {
                    b.HasOne("Interface.Entities.LogLine", "LogLine")
                        .WithMany("Items")
                        .HasForeignKey("LogLineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
