language: csharp
solution: GDAXClient.sln
script:
  - xbuild /p:Configuration=Release GDAXClient.sln
  - mono ./packages/Machine.Specifications.Runner.Console.0.9.3/tools/mspec.exe ./GDAXClient.Specs/bin/Release/GDAXClient.Specs.dll
